범주형(categorical) 데이터 인코딩 
1. 라벨 인코딩(Label Encoding)
- 범주형 데이터를 연속된 숫자로 변환 시키는 전처리 기법
2. One-Hot-Encoding 

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns



In [2]:
tips = sns.load_dataset('tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
print('Tips Categories:\n',tips['day'].unique())

Tips Categories:
 ['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']


In [4]:
from sklearn.preprocessing import LabelEncoder
# step1. 인코딩할 데이터 준비
items = tips['day']
# step2. LabelEncoder 객체 생성
encoder = LabelEncoder()
# step3. .fit() 데이터 전달 및 분포도
encoder.fit(items)
# step4. .transform() 인코딩할 데이터 변환
labels = encoder.transform(items)


In [6]:
labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [9]:
classes = encoder.classes_  #classes_ : 변환된 인코딩 값에 대한 원본 값을 가지고 있음
print('Encoding classes:',classes) 

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [11]:
inverse_result = encoder.inverse_transform([2])
print('Encoding classes:',inverse_result) #decoding

Encoding classes: ['Sun']


In [12]:
# onehotencoder 의 입력 데이터는 2차원 데이터만 가능, 변환 필요(reshape)
print(tips.shape)

(244, 7)

----


OneHotEncoding
1. 인코딩할 데이터 확인 및 라벨인코딩
2. OneHotEncoder의 입력 데이터는 2차원으로 reshape 필요
    - (22,) -> (22,1) (일차원에서 이차원으로 변환된 꼴임.)

In [13]:
labels = labels.reshape(-1,1) #reshape 과정

In [16]:
from sklearn.preprocessing import OneHotEncoder

#OneHotEncoder 객체 생성
one_hot_encoder = OneHotEncoder()

# .fit 인코딩 데이터 전달 
one_hot_encoder.fit(labels)

#.transform 데이터 변환
one_hot_encoder = one_hot_encoder.transform(labels) 

In [18]:
one_hot_encoder

<244x4 sparse matrix of type '<class 'numpy.float64'>'
	with 244 stored elements in Compressed Sparse Row format>

In [17]:
print('OneHotEncoding Result: ', one_hot_encoder.toarray()) #toarray로 배열 모양으로 출력

OneHotEncoding Result:  [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 

In [24]:
#.categorise_ 속성을 통해 인코딩 데이터의 실제 클래스 확인 가능 
onehot_classes = one_hot_encoder.categories_
onehot_classes

AttributeError: categories_ not found